### ISSUE TITLE
Extend readme with a how-to use :)

### ISSUE THREAD

**Issue by FlorianO** [riemann/riemann-postgresql#1]
Right now, i get an 

```
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- /home/ubuntu/riemann-postgresql/lib/riemann/tools (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from ./riemann-postgresql:6:in `<main>'
```

when i try to start it.
Is there anything i have to do before i can use it?

**Comment by pradeepchhetri** [comment]
Hi @FlorianO 

Sorry for the late reply. I have updated the README . Can you kindly follow the steps and try to install. I tried my best to cover all edge-cases. But I would love to know how your installation will go through using those steps.

**Comment by jamtur01** [comment]
Closing for now.
